---
#
# Install Java 8
#
- name: Add Java repo
  apt_repository:
    repo: ppa:webupd8team/java
- name: Select Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
- name: Install Java 8
  apt:
    name: oracle-java8-installer
    state: present
    update_cache: yes
- name: ensure
  shell: dpkg -i oracle-java*-installer*  
