---
#
# Install ElasticSearch
#

- name: Add ElasticSearch apt-key
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add ElasticSearch repo
  apt_repository:
    repo: "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
    state: present

- name: Update repos cache and install ElasticSearch
  apt:
    name: elasticsearch
    update_cache: yes

- name: Update ElasticSearch config
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'
- name: Enable autostart
  shell: update-rc.d elasticsearch defaults 95 10

- name: Restart ElasticSearch
  service:
    name: elasticsearch
    state: restarted
